parameters:
  - name: serviceName
    default: ""
  - name: pushArtefacts
    default: false

jobs:
  - job: Build
    displayName: Build job - ${{ parameters.serviceName }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: 'docker-base-$(Build.BuildId)'
    - task: Docker@0
      displayName: 'Retrieve base docker image from artifacts'
      inputs:
        action: 'Run a Docker command'
        customCommand: 'load -i $(Pipeline.Workspace)/docker-base-$(Build.BuildId)/image_base_$(Build.BuildId).tar'
    - download: current
      artifact: 'docker-design-system-$(Build.BuildId)'
    - task: Docker@0
      displayName: 'Retrieve base docker image from artifacts'
      inputs:
        action: 'Run a Docker command'
        customCommand: 'load -i $(Pipeline.Workspace)/docker-design-system-$(Build.BuildId)/image_design_system_$(Build.BuildId).tar'
    - task: Docker@2
      displayName: Build - ${{ parameters.serviceName }}
      inputs:
        command: build
        repository: life-events-${{ parameters.serviceName }}
        dockerfile: apps/${{ parameters.serviceName }}/Dockerfile
        buildContext: '$(Build.SourcesDirectory)'
        arguments: '--build-arg "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$(nextPublicStripePublishableKey)" --build-arg "NEXT_PUBLIC_HOST_URL=$(nextPublicHostUrl)" --build-arg "NEXT_PUBLIC_API_ENDPOINT=$(nextPublicApiEndpoint)"'
    - task: Docker@0
      displayName: 'Run a Docker command'
      condition: ${{ parameters.pushArtefacts }}
      inputs:
        action: 'Run a Docker command'
        customCommand: 'save -o $(Build.ArtifactStagingDirectory)/image_${{ parameters.serviceName }}_$(Build.BuildId).tar life-events-${{ parameters.serviceName }}:$(Build.BuildId)'
    - publish:  $(Build.ArtifactStagingDirectory)
      condition: ${{ parameters.pushArtefacts }}
      artifact: 'docker-${{ parameters.serviceName }}-$(Build.BuildId)'