jobs:
  - job: Dependencies
    displayName: Download container dependencies
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: 'docker-base-$(Build.BuildId)'
    - task: Docker@0
      displayName: 'Retrieve base docker image from artifacts'
      inputs:
        action: 'Run a Docker command'
        customCommand: 'load -i $(Pipeline.Workspace)/docker-base-$(Build.BuildId)/image_base_$(Build.BuildId).tar'
    - download: current
      artifact: 'docker-design-system-$(Build.BuildId)'
    - task: Docker@0
      displayName: 'Retrieve base docker image from artifacts'
      inputs:
        action: 'Run a Docker command'
        customCommand: 'load -i $(Pipeline.Workspace)/docker-design-system-$(Build.BuildId)/image_design_system_$(Build.BuildId).tar'