parameters:
  - name: dependency
    default: ""
  - name: dependencies
    type: object
    default:
      - analytics
      - api-auth
      - auth
      - building-blocks-sdk
      - design-system
      - error-handler
      - feature-flags
      - logging-wrapper
      - messages
      - nextjs-logging-wrapper
      - shared-components
      - shared-errors


jobs:
  - job: Run_dependencies_tests
    displayName: Run unit tests for dependencies
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: install
    - ${{ each dependency in split(replace(variables.dependencies, ' ', ''), ',') }}:
    - task: CmdLine@2
      displayName: 'Run test for ${{ parameters.dependency }}'
      inputs:
        script: npm run test  --prefix packages${{ parameters.dependency }}
    - ${{ each dependency in split(replace(variables.dependencies, ' ', ''), ',') }}:   
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'packages${{ parameters.dependency }}/results.xml'
        testRunTitle: 'Unit test results for ${{ parameters.dependency }}:$(Build.BuildId)'
      condition: succeededOrFailed()

 