openapi: 3.0.3
info:
  title: OGCIO Payment API
  description: API for OGCIO Payment Service
  version: 0.1.0
components:
  schemas: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: Default Response
  /api/v1/providers/:
    post:
      tags:
        - Providers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  anyOf:
                    - type: string
                      enum:
                        - banktransfer
                    - type: string
                      enum:
                        - openbanking
                    - type: string
                      enum:
                        - stripe
                data: {}
              required:
                - name
                - type
                - data
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
    get:
      tags:
        - Providers
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    type:
                      anyOf:
                        - type: string
                          enum:
                            - banktransfer
                        - type: string
                          enum:
                            - openbanking
                        - type: string
                          enum:
                            - stripe
                    data: {}
                    status:
                      type: string
                  required:
                    - id
                    - name
                    - type
                    - data
                    - status
  /api/v1/providers/{providerId}:
    get:
      tags:
        - Providers
      parameters:
        - schema:
            type: string
          in: path
          name: providerId
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  type:
                    type: string
                  data: {}
                  status:
                    type: string
                required:
                  - id
                  - name
                  - type
                  - data
                  - status
    put:
      tags:
        - Providers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                data: {}
                status:
                  anyOf:
                    - type: string
                      enum:
                        - connected
                    - type: string
                      enum:
                        - disconnected
              required:
                - name
                - data
                - status
        required: true
      parameters:
        - schema:
            type: string
          in: path
          name: providerId
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                required:
                  - ok
tags:
  - name: Providers
