FROM node:lts-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV LOG_LEVEL=trace

COPY ./package*.json /app/
COPY ./apps/web/package*.json /app/apps/web/
COPY ./packages/design-system/package*.json /app/packages/design-system/
RUN npm ci

COPY ./apps/web/ /app/apps/web/
COPY ./packages/design-system/ /app/packages/design-system/

EXPOSE 80

CMD [ "npm", "--prefix", "apps/web",  "run", "dev" ]