version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Security updates only
    open-pull-requests-limit: 0
    versioning-strategy: increase
    commit-message:
      prefix: "[npm]"
