trigger: none
pr: none

schedules: 
- cron: '0 20 * * 0'   # 8 pm daily test run
  branches: 
    include: 
    - dev

# Services object is now defined per environment. 
# Check the variables file for the desired environment!
variables:
  - template: pipeline-variables/dev.yml

resources:
  repositories:
    - repository: pipeline-templates
      type: github
      name: ogcio/building-blocks-pipelines
      ref: perfTests
      endpoint: ogcio

stages:
  - stage: Start_Tests
    displayName: Start Tests
    pool: 'Openshift'
    jobs:
      - job: start
        displayName: start
        steps:
          - task: CmdLine@2
            displayName: Start 
            inputs:
              script: "echo \"Starting test run\" && exit 0"
  - ${{ each serviceName in split(replace(variables.services, ' ', ''), ',') }}:
    - stage: Regression_Tests_${{ replace(serviceName, '-', '_') }}
      displayName: Run regression tests - ${{ serviceName }}
      pool: 'Openshift'
      jobs:
        - template: test/regression_test.yml@pipeline-templates
          parameters:
            serviceName: ${{ serviceName }}
            testPath: './apps/'
    - stage: Performance_Tests_${{ replace(serviceName, '-', '_') }}
      displayName: Run performance tests - ${{ serviceName }}
      pool: 'Openshift'
      dependsOn: Regression_Tests_${{ replace(serviceName, '-', '_') }}
      jobs:
        - template: test/performance_test.yml@pipeline-templates
          parameters:
            serviceName: ${{ serviceName }}
            testPath: './apps/'

