trigger:
  - dev
  - uat
  - sta

pr:
  autoCancel: true
  branches:
    include:
      - "*"

# Services object is now defined per environment. 
# Check the variables file for the desired environment!
parameters:
  - name: buildBranches
    type: object
    default: ["dev", "sta", "uat"]

  - name: validEnvironments
    type: object
    displayName: List of valid environments to deploy (do not change)
    default: ['dev','sta', 'uat', 'prd']

  - name: vmImage
    type: string
    default: "ubuntu-22.04"

variables:
  - name: pushArtefacts
    value: ${{ containsValue(parameters.buildBranches, variables['Build.SourceBranchName']) }}
  - ${{ if containsValue(parameters.validEnvironments ,variables['Build.SourceBranchName']) }}:
    - template: pipeline-variables/${{ coalesce(variables['Build.SourceBranchName'], 'fallback') }}.yml
  - ${{ else }}:
    - template: pipeline-variables/dev.yml

stages:
  - stage: securityScan
    displayName: Security Scans
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - job: gitLeaksScan
        displayName: GitLeaks Scan
        steps:
          - task: DockerInstaller@0
            displayName: Docker Installer
            inputs:
              dockerVersion: 17.09.0-ce
              releaseType: stable
          - script: |
              docker run --rm -i -v "$(pwd):/src" zricethezav/gitleaks:v8.18.4 detect --source="/src" -c "src/.gitleaks.toml"  --no-git -v
            displayName: GitLeaks Scan
      - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        - job: bearerScan
          displayName: Bearer
          continueOnError: true
          steps:
            - task: DockerInstaller@0
              displayName: Docker Installer
              inputs:
                dockerVersion: 17.09.0-ce
                releaseType: stable
            - script: |
                docker run --rm -v $(pwd):/tmp/scan bearer/bearer:latest-amd64 scan --no-color --hide-progress-bar --fail-on-severity critical,high /tmp/scan
              displayName: Code Scan
  - stage: BuildDeps
    displayName: Build service dependencies
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - template: pipeline-templates/build_dependencies.yml
  - ${{ each serviceName in split(replace(variables.services, ' ', ''), ',') }}:
    - stage: Build_${{ replace(serviceName, '-', '_') }}
      displayName: Build ${{ serviceName }}
      pool:
        vmImage: ${{ parameters.vmImage }}
      dependsOn: 
        - securityScan
        - BuildDeps
      jobs:  
      - template: pipeline-templates/build_service.yml
        parameters:
          serviceName: ${{ serviceName }}
          pushArtefacts: ${{ variables.pushArtefacts }}
  - stage: EnvApproval
    displayName: Approvals for deployments - ${{ upper(variables.environment) }}
    dependsOn:
      - ${{ each serviceName in split(replace(variables.services, ' ', ''), ',') }}:
        - Build_${{ replace(serviceName, '-', '_') }}
    condition: ${{ variables.pushArtefacts }}
    jobs:
    - deployment: VerifyDeployment
      displayName: Verify conditions for deployment
      environment: ${{ variables.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                date
              displayName: Show current date
  - ${{ each serviceName in split(replace(variables.services, ' ', ''), ',') }}:
    - stage: Push_${{ replace(serviceName, '-', '_') }}
      displayName: Push ${{ serviceName }} to ECR
      pool:
        vmImage: ${{ parameters.vmImage }}
      dependsOn: 
        - EnvApproval
      condition: and(${{ variables.pushArtefacts }}, succeeded())
      jobs:
      - template: pipeline-templates/push_image.yml
        parameters:
          awsServiceConnection: ${{ variables.awsServiceConnection }}
          awsRegion: ${{ variables.awsRegion }}
          serviceName: ${{ serviceName }}
    - stage: Deploy_${{ replace(serviceName, '-', '_') }}
      displayName: Deploy to ECS - ${{ serviceName }}
      pool:
        vmImage: ${{ parameters.vmImage }}
      dependsOn: Push_${{ replace(serviceName, '-', '_') }}
      jobs:
      - template: pipeline-templates/deploy_ecs.yml
        parameters:
          awsServiceConnection: ${{ variables.awsServiceConnection }}
          awsRegion: ${{ variables.awsRegion }}
          serviceName: ${{ serviceName }}