trigger:
  - dev
  - uat
  - sta

pr:
  autoCancel: true
  branches:
    include:
      - "*"

parameters:
  - name: services
    type: object
    default: ["web", "mock-api", "payments", "messaging", "messaging-api", "payments-api", "profile", "profile-api"]

  - name: envBranches
    type: object
    default: ["refs/heads/dev", "refs/heads/sta", "refs/heads/uat"]

variables:
  - template: pipeline-variables/dev.yml
  - name: pushArtefacts
    value: ${{ containsValue(parameters.envBranches, variables['Build.SourceBranch']) }}

stages:
  - stage: securityScan
    displayName: Security Scans
    jobs:
      - job: gitLeaksScan
        #continueOnError: True
        pool:
          vmImage: "ubuntu-22.04"
        displayName: GitLeaks Scan
        steps:
          - task: DockerInstaller@0
            displayName: Docker Installer
            inputs:
              dockerVersion: 17.09.0-ce
              releaseType: stable
          - script: |
              docker pull zricethezav/gitleaks:v8.10.3
              docker run --rm -i -v "$(pwd):/src" zricethezav/gitleaks:v8.10.3 detect --source="/src" -c "src/.gitleaks.toml"  --no-git -v
            displayName: GitLeaks Scan
  - stage: BuildDeps
    displayName: Build service dependencies
    jobs:
      - template: pipeline-templates/build_dependencies.yml
  - ${{ each serviceName in parameters.services }}:
    - stage: Build_${{ replace(serviceName, '-', '_') }}
      displayName: Build ${{ serviceName }}
      dependsOn: 
        - securityScan
        - BuildDeps
      jobs:  
      - template: pipeline-templates/build_service.yml
        parameters:
          serviceBuildName: ${{ serviceName }}
    - stage: Push_${{ replace(serviceName, '-', '_') }}
      displayName: Push ${{ serviceName }} to ECR
      dependsOn: Build_${{ replace(serviceName, '-', '_') }}
      condition: and(succeeded(), eq(variables.pushArtefacts, true))
      jobs:
      - job: Push
        displayName: Push - ${{ serviceName }}
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - download: current
          artifact: 'docker-${{ serviceName }}-$(Build.BuildId)'
        - task: Docker@0
          displayName: 'Retrieve docker image from artifacts'
          inputs:
            action: 'Run a Docker command'
            customCommand: 'load -i $(Pipeline.Workspace)/docker-${{ serviceName }}-$(Build.BuildId)/image_${{ serviceName }}_$(Build.BuildId).tar'
        - task: ECRPushImage@1
          inputs:
            awsCredentials: $(awsServiceConnection)
            regionName: $(awsRegion)
            imageSource: 'imagename'
            sourceImageName: life-events-${{ serviceName }}
            sourceImageTag: $(Build.BuildId)
            pushTag: $(Build.SourceBranchName)
            repositoryName: life-events-${{ serviceName }}
        - task: AWSCLI@1
          inputs:
            awsCredentials: $(awsServiceConnection)
            regionName: $(awsRegion)
            awsCommand: 'ecs'
            awsSubCommand: 'update-service'
            awsArguments: '--force-new-deployment --cluster life-events-ecs --service ${{ serviceName }}-service'
