trigger:
  - dev
  - uat
  - sta

pr:
  autoCancel: true
  branches:
    include:
      - "*"

# Services object is now defined per environment. 
# Check the variables file for the desired environment!
parameters:
  - name: buildBranches
    type: object
    default: ["dev", "sta", "uat"]

  - name: validEnvironments
    type: object
    displayName: List of valid environments to deploy (do not change)
    default: ['dev','sta', 'uat', 'prd']

variables:
  - name: pushArtefacts
    value: ${{ containsValue(parameters.buildBranches, variables['Build.SourceBranchName']) }}
  - ${{ if containsValue(parameters.validEnvironments ,variables['Build.SourceBranchName']) }}:
    - template: pipeline-variables/${{ coalesce(variables['Build.SourceBranchName'], 'fallback') }}.yml
  - ${{ else }}:
    - template: pipeline-variables/dev.yml

resources:
  repositories:
    - repository: pipeline-templates
      type: github
      name: ogcio/building-blocks-pipelines
      ref: main
      endpoint: ogcio

stages:
  - stage: securityScan
    displayName: Security Scans
    jobs:
      - template: security/gitleaks.yml@pipeline-templates
  - stage: BuildDeps
    displayName: Build service dependencies
    jobs:
      - template: pipeline-templates/build_dependencies.yml
  - ${{ each serviceName in split(replace(variables.services, ' ', ''), ',') }}:
    - stage: Build_${{ replace(serviceName, '-', '_') }}
      displayName: Build ${{ serviceName }}
      dependsOn: 
        - securityScan
        - BuildDeps
      jobs:  
      - template: pipeline-templates/build_service.yml
        parameters:
          serviceName: ${{ serviceName }}
          pushArtefacts: ${{ variables.pushArtefacts }}
  - stage: EnvApproval
    displayName: Approvals for deployments - ${{ upper(variables.environment) }}
    dependsOn:
      - ${{ each serviceName in split(replace(variables.services, ' ', ''), ',') }}:
        - Build_${{ replace(serviceName, '-', '_') }}
    condition: ${{ variables.pushArtefacts }}
    jobs:
    - deployment: VerifyDeployment
      displayName: Verify conditions for deployment
      environment: ${{ variables.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            - script: |
                date
              displayName: Show current date
  - ${{ each serviceName in split(replace(variables.services, ' ', ''), ',') }}:
    - stage: Push_${{ replace(serviceName, '-', '_') }}
      displayName: Push ${{ serviceName }} to ECR
      dependsOn: 
        - EnvApproval
      condition: and(${{ variables.pushArtefacts }}, succeeded())
      jobs:
      - template: pipeline-templates/push_image.yml
        parameters:
          awsServiceConnection: ${{ variables.awsServiceConnection }}
          awsRegion: ${{ variables.awsRegion }}
          serviceName: ${{ serviceName }}
    - stage: Deploy_${{ replace(serviceName, '-', '_') }}
      displayName: Deploy to ECS - ${{ serviceName }}
      dependsOn: Push_${{ replace(serviceName, '-', '_') }}
      jobs:
      - template: pipeline-templates/deploy_ecs.yml
        parameters:
          awsServiceConnection: ${{ variables.awsServiceConnection }}
          awsRegion: ${{ variables.awsRegion }}
          serviceName: ${{ serviceName }}