services:
  postgresql:
    image: postgres:15.2-alpine
    restart: always
    environment:
      PGUSER: ${POSTGRES_USER:-postgres} # will use current os user otherwise.
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    healthcheck:
      test: 'wget -O - http://127.0.0.1:1080/healthz || exit 1'

  localstack:
    image: localstack/localstack:2.3.2
    ports:
      - 4566:4566
    environment:
      SERVICES: "s3,secretsmanager"
      DATA_DIR: "/tmp/localstack/data"
      FILES_S3_BUCKET: "life-events-files"
      IMAGES_S3_BUCKET: "life-events-images"
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh' # ready hook
      
volumes:
  db:
    driver: local
