services:
  postgresql:
    image: postgres:15.2-alpine
    restart: always
    environment:
      PGUSER: ${POSTGRES_USER:-postgres} # will use current os user otherwise.
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    healthcheck:
      test: 'wget -O - http://127.0.0.1:1080/healthz || exit 1'

  clamav:
    build: ./clamav
    image: clamav
    entrypoint: ./init-unprivileged
    volumes:
      - clamav:/tmp/
    ports:
      - 3310:3310

  localstack:
    image: localstack/localstack:2.3.2
    ports:
      - 4566:4566
    environment:
      SERVICES: "s3,secretsmanager, kms"
      FILES_S3_BUCKET: "life-events-files"
      IMAGES_S3_BUCKET: "life-events-images"
      FILE_UPLOAD_SERVICE_BUCKET: "file-upload-service"
      LOCALSTACK_ENDPOINT: "http://localhost:4566"
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh' # ready hook
        
volumes:
  db:
    driver: local
  clamav:

# custom network to be able to reach Logto running on same network with another Docker Compose file
networks:
  logto_network:
    external: true
