services:
  postgresql:
    extends:
      file: docker-compose.yaml
      service: postgresql

  maildev:
    extends:
      file: docker-compose.yaml
      service: maildev
  
  clamav:
    extends:
      file: docker-compose.yaml
      service: clamav

  localstack:
    extends:
      file: docker-compose.yaml
      service: localstack
volumes:
  db:
    driver: local
  clamav:

# custom network to be able to reach Logto running on same network with another Docker Compose file
networks:
  logto_network:
    external: true
