services:
  postgresql:
    extends:
      file: docker-compose.yaml
      service: postgresql

  maildev:
    extends:
      file: docker-compose.yaml
      service: maildev

  localstack:
    extends:
      file: docker-compose.yaml
      service: localstack

  scheduler_migrations:
    image: scheduler-api-container:latest
    build:
      context: .
      dockerfile: ./apps/scheduler-api/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=scheduler
    command: [ "npm", "run", "migrate:scheduler-api" ]
    depends_on:
      postgresql:
        condition: service_healthy

  scheduler:
    image: scheduler-api-container:latest
    ports:
      - 8005:8005
    env_file:
      - './apps/scheduler-api/.env'
    environment:
      - POSTGRES_HOST=postgresql
    depends_on:
      scheduler_migrations:
        condition: service_completed_successfully
volumes:
  db:
    driver: local
