BEGIN;

ALTER TABLE user_details
ALTER COLUMN title DROP NOT NULL,
ALTER COLUMN date_of_birth SET DATA TYPE TIMESTAMPTZ USING date_of_birth::TIMESTAMPTZ,
ALTER COLUMN date_of_birth DROP NOT NULL,
ALTER COLUMN ppsn DROP NOT NULL,
ALTER COLUMN gender DROP NOT NULL,
ALTER COLUMN phone DROP NOT NULL,
ADD COLUMN ppsn_visible BOOLEAN DEFAULT FALSE,
ADD COLUMN consent_to_prefill_data BOOLEAN DEFAULT FALSE;

COMMIT;