openapi: 3.0.3
info:
  title: OGCIO File Upload API
  description: API for OGCIO file upload service
  version: 0.1.0
components:
  schemas: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: Default Response
  /api/v1/files/:
    post:
      tags:
        - Files
      requestBody:
        content:
          multipart/form-data:
            schema:
              anyOf:
                - {}
                - {}
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                    required:
                      - id
                required:
                  - data
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        5XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
  /api/v1/files/{id}:
    get:
      tags:
        - Files
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        5XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
  /api/v1/metadata/:
    get:
      tags:
        - Metadata
      parameters:
        - schema:
            type: string
          in: query
          name: userId
          required: false
        - schema:
            type: string
          in: query
          name: organizationId
          required: false
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        fileName:
                          type: string
                        id:
                          type: string
                        key:
                          type: string
                        ownerId:
                          type: string
                        fileSize:
                          type: number
                        mimeType:
                          type: string
                        createdAt:
                          type: string
                        lastScan:
                          type: string
                        deleted:
                          default: false
                          type: boolean
                        infected:
                          type: boolean
                        infectionDescription:
                          type: string
                        antivirusDbVersion:
                          type: string
                        sharedWith:
                          type: array
                          items:
                            type: string
                        expiresAt:
                          type: string
                      required:
                        - fileName
                        - key
                        - ownerId
                        - fileSize
                        - mimeType
                        - createdAt
                        - lastScan
                        - infected
                required:
                  - data
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        5XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
    delete:
      tags:
        - Metadata
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
              required:
                - fileId
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                    required:
                      - id
                required:
                  - data
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        5XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
  /api/v1/metadata/{id}:
    get:
      tags:
        - Metadata
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      fileName:
                        type: string
                      id:
                        type: string
                      key:
                        type: string
                      ownerId:
                        type: string
                      fileSize:
                        type: number
                      mimeType:
                        type: string
                      createdAt:
                        type: string
                      lastScan:
                        type: string
                      deleted:
                        default: false
                        type: boolean
                      infected:
                        type: boolean
                      infectionDescription:
                        type: string
                      antivirusDbVersion:
                        type: string
                      sharedWith:
                        type: array
                        items:
                          type: string
                      expiresAt:
                        type: string
                    required:
                      - fileName
                      - key
                      - ownerId
                      - fileSize
                      - mimeType
                      - createdAt
                      - lastScan
                      - infected
                required:
                  - data
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        5XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
  /api/v1/metadata/share/:
    post:
      tags:
        - Metadata share
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
                userId:
                  type: string
              required:
                - fileId
                - userId
        required: true
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      fileId:
                        type: string
                      userId:
                        type: string
                    required:
                      - fileId
                      - userId
                required:
                  - data
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        5XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
    delete:
      tags:
        - Metadata share
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
                userId:
                  type: string
              required:
                - fileId
                - userId
        required: true
      responses:
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        5XX:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
tags:
  - name: FileUploadApi
