openapi: 3.0.3
info:
  title: OGCIO File Upload API
  description: API for OGCIO file upload servce
  version: 0.1.0
components:
  schemas: {}
paths:
  /files/:
    post:
      tags:
        - Files
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  request_id:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - request_id
                  - name
    get:
      tags:
        - Files
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    url:
                      type: string
                    key:
                      type: string
                    size:
                      type: number
                  required:
                    - url
                    - key
                    - size
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  request_id:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - request_id
                  - name
  /files/{key}:
    delete:
      tags:
        - Files
      parameters:
        - schema:
            type: string
          in: path
          name: key
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  request_id:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - request_id
                  - name
    get:
      tags:
        - Files
      parameters:
        - schema:
            type: string
          in: path
          name: key
          required: true
      responses:
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  request_id:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - request_id
                  - name
  /health:
    get:
      responses:
        "200":
          description: Default Response
tags:
  - name: FileUploadApi
