/* tslint:disable */
/* eslint-disable */
/**
 * OGCIO Payment API
 * API for OGCIO Payment Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "./common";
import type { RequestArgs } from "./base";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "./base";

/**
 *
 * @export
 * @interface ApiV1ProvidersGet200ResponseInner
 */
export interface ApiV1ProvidersGet200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersGet200ResponseInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersGet200ResponseInner
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersGet200ResponseInner
   */
  type: string;
  /**
   *
   * @type {any}
   * @memberof ApiV1ProvidersGet200ResponseInner
   */
  data: any;
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersGet200ResponseInner
   */
  status: string;
}
/**
 *
 * @export
 * @interface ApiV1ProvidersPost200Response
 */
export interface ApiV1ProvidersPost200Response {
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersPost200Response
   */
  id: string;
}
/**
 *
 * @export
 * @interface ApiV1ProvidersPostRequest
 */
export interface ApiV1ProvidersPostRequest {
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersPostRequest
   */
  name: string;
  /**
   *
   * @type {ApiV1ProvidersPostRequestType}
   * @memberof ApiV1ProvidersPostRequest
   */
  type: ApiV1ProvidersPostRequestType;
  /**
   *
   * @type {any}
   * @memberof ApiV1ProvidersPostRequest
   */
  data: any;
}
/**
 *
 * @export
 * @interface ApiV1ProvidersPostRequestType
 */
export interface ApiV1ProvidersPostRequestType {}
/**
 *
 * @export
 * @interface ApiV1ProvidersProviderIdGet400Response
 */
export interface ApiV1ProvidersProviderIdGet400Response {
  /**
   *
   * @type {number}
   * @memberof ApiV1ProvidersProviderIdGet400Response
   */
  statusCode: number;
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersProviderIdGet400Response
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersProviderIdGet400Response
   */
  error: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersProviderIdGet400Response
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersProviderIdGet400Response
   */
  time: string;
}
/**
 *
 * @export
 * @interface ApiV1ProvidersProviderIdPut200Response
 */
export interface ApiV1ProvidersProviderIdPut200Response {
  /**
   *
   * @type {boolean}
   * @memberof ApiV1ProvidersProviderIdPut200Response
   */
  ok: boolean;
}
/**
 *
 * @export
 * @interface ApiV1ProvidersProviderIdPutRequest
 */
export interface ApiV1ProvidersProviderIdPutRequest {
  /**
   *
   * @type {string}
   * @memberof ApiV1ProvidersProviderIdPutRequest
   */
  name: string;
  /**
   *
   * @type {any}
   * @memberof ApiV1ProvidersProviderIdPutRequest
   */
  data: any;
  /**
   *
   * @type {ApiV1ProvidersProviderIdPutRequestStatus}
   * @memberof ApiV1ProvidersProviderIdPutRequest
   */
  status: ApiV1ProvidersProviderIdPutRequestStatus;
}
/**
 *
 * @export
 * @interface ApiV1ProvidersProviderIdPutRequestStatus
 */
export interface ApiV1ProvidersProviderIdPutRequestStatus {}
/**
 *
 * @export
 * @interface ApiV1RequestsGet200ResponseInner
 */
export interface ApiV1RequestsGet200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInner
   */
  paymentRequestId: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInner
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInner
   */
  description: string;
  /**
   *
   * @type {number}
   * @memberof ApiV1RequestsGet200ResponseInner
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInner
   */
  reference: string;
  /**
   *
   * @type {Array<ApiV1RequestsGet200ResponseInnerProvidersInner>}
   * @memberof ApiV1RequestsGet200ResponseInner
   */
  providers: Array<ApiV1RequestsGet200ResponseInnerProvidersInner>;
}
/**
 *
 * @export
 * @interface ApiV1RequestsGet200ResponseInnerProvidersInner
 */
export interface ApiV1RequestsGet200ResponseInnerProvidersInner {
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInnerProvidersInner
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInnerProvidersInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInnerProvidersInner
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInnerProvidersInner
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInnerProvidersInner
   */
  status: string;
  /**
   *
   * @type {any}
   * @memberof ApiV1RequestsGet200ResponseInnerProvidersInner
   */
  data: any;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsGet200ResponseInnerProvidersInner
   */
  createdAt: string;
}
/**
 *
 * @export
 * @interface ApiV1RequestsPostRequest
 */
export interface ApiV1RequestsPostRequest {
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsPostRequest
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsPostRequest
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsPostRequest
   */
  reference: string;
  /**
   *
   * @type {number}
   * @memberof ApiV1RequestsPostRequest
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsPostRequest
   */
  redirectUrl: string;
  /**
   *
   * @type {boolean}
   * @memberof ApiV1RequestsPostRequest
   */
  allowAmountOverride: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ApiV1RequestsPostRequest
   */
  allowCustomAmount: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof ApiV1RequestsPostRequest
   */
  providers: Array<string>;
}
/**
 *
 * @export
 * @interface ApiV1RequestsPutRequest
 */
export interface ApiV1RequestsPutRequest {
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsPutRequest
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsPutRequest
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsPutRequest
   */
  reference: string;
  /**
   *
   * @type {number}
   * @memberof ApiV1RequestsPutRequest
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsPutRequest
   */
  redirectUrl: string;
  /**
   *
   * @type {boolean}
   * @memberof ApiV1RequestsPutRequest
   */
  allowAmountOverride: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ApiV1RequestsPutRequest
   */
  allowCustomAmount: boolean;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsPutRequest
   */
  paymentRequestId: string;
  /**
   *
   * @type {ApiV1RequestsPutRequestProvidersUpdate}
   * @memberof ApiV1RequestsPutRequest
   */
  providersUpdate: ApiV1RequestsPutRequestProvidersUpdate;
}
/**
 *
 * @export
 * @interface ApiV1RequestsPutRequestProvidersUpdate
 */
export interface ApiV1RequestsPutRequestProvidersUpdate {
  /**
   *
   * @type {Array<string>}
   * @memberof ApiV1RequestsPutRequestProvidersUpdate
   */
  toDisable: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof ApiV1RequestsPutRequestProvidersUpdate
   */
  toCreate: Array<string>;
}
/**
 *
 * @export
 * @interface ApiV1RequestsRequestIdGet200Response
 */
export interface ApiV1RequestsRequestIdGet200Response {
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsRequestIdGet200Response
   */
  paymentRequestId: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsRequestIdGet200Response
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsRequestIdGet200Response
   */
  description: string;
  /**
   *
   * @type {number}
   * @memberof ApiV1RequestsRequestIdGet200Response
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsRequestIdGet200Response
   */
  reference: string;
  /**
   *
   * @type {Array<ApiV1RequestsGet200ResponseInnerProvidersInner>}
   * @memberof ApiV1RequestsRequestIdGet200Response
   */
  providers: Array<ApiV1RequestsGet200ResponseInnerProvidersInner>;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsRequestIdGet200Response
   */
  redirectUrl: string;
  /**
   *
   * @type {boolean}
   * @memberof ApiV1RequestsRequestIdGet200Response
   */
  allowAmountOverride: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ApiV1RequestsRequestIdGet200Response
   */
  allowCustomAmount: boolean;
}
/**
 *
 * @export
 * @interface ApiV1RequestsRequestIdTransactionsGet200ResponseInner
 */
export interface ApiV1RequestsRequestIdTransactionsGet200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsRequestIdTransactionsGet200ResponseInner
   */
  transactionId: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsRequestIdTransactionsGet200ResponseInner
   */
  status: string;
  /**
   *
   * @type {number}
   * @memberof ApiV1RequestsRequestIdTransactionsGet200ResponseInner
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsRequestIdTransactionsGet200ResponseInner
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1RequestsRequestIdTransactionsGet200ResponseInner
   */
  title: string;
}
/**
 *
 * @export
 * @interface ApiV1TransactionsPost200Response
 */
export interface ApiV1TransactionsPost200Response {
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsPost200Response
   */
  transactionId: string;
}
/**
 *
 * @export
 * @interface ApiV1TransactionsPostRequest
 */
export interface ApiV1TransactionsPostRequest {
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsPostRequest
   */
  paymentRequestId: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsPostRequest
   */
  extPaymentId: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsPostRequest
   */
  integrationReference: string;
  /**
   *
   * @type {number}
   * @memberof ApiV1TransactionsPostRequest
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsPostRequest
   */
  paymentProviderId: string;
  /**
   *
   * @type {ApiV1TransactionsTransactionIdGet200ResponseUserData}
   * @memberof ApiV1TransactionsPostRequest
   */
  userData: ApiV1TransactionsTransactionIdGet200ResponseUserData;
}
/**
 *
 * @export
 * @interface ApiV1TransactionsTransactionIdGet200Response
 */
export interface ApiV1TransactionsTransactionIdGet200Response {
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdGet200Response
   */
  transactionId: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdGet200Response
   */
  status: string;
  /**
   *
   * @type {number}
   * @memberof ApiV1TransactionsTransactionIdGet200Response
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdGet200Response
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdGet200Response
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdGet200Response
   */
  extPaymentId: string;
  /**
   *
   * @type {ApiV1TransactionsTransactionIdGet200ResponseUserData}
   * @memberof ApiV1TransactionsTransactionIdGet200Response
   */
  userData: ApiV1TransactionsTransactionIdGet200ResponseUserData;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdGet200Response
   */
  providerName: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdGet200Response
   */
  providerType: string;
}
/**
 *
 * @export
 * @interface ApiV1TransactionsTransactionIdGet200ResponseUserData
 */
export interface ApiV1TransactionsTransactionIdGet200ResponseUserData {
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdGet200ResponseUserData
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdGet200ResponseUserData
   */
  email: string;
}
/**
 *
 * @export
 * @interface ApiV1TransactionsTransactionIdPatchRequest
 */
export interface ApiV1TransactionsTransactionIdPatchRequest {
  /**
   *
   * @type {string}
   * @memberof ApiV1TransactionsTransactionIdPatchRequest
   */
  status: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthGet: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/health`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async healthGet(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.healthGet(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.healthGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DefaultApiFp(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthGet(options?: any): AxiosPromise<void> {
      return localVarFp
        .healthGet(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public healthGet(options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .healthGet(options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * PaymentRequestsApi - axios parameter creator
 * @export
 */
export const PaymentRequestsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsGet: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/requests/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ApiV1RequestsPostRequest} apiV1RequestsPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsPost: async (
      apiV1RequestsPostRequest: ApiV1RequestsPostRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiV1RequestsPostRequest' is not null or undefined
      assertParamExists(
        "apiV1RequestsPost",
        "apiV1RequestsPostRequest",
        apiV1RequestsPostRequest,
      );
      const localVarPath = `/api/v1/requests/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiV1RequestsPostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ApiV1RequestsPutRequest} apiV1RequestsPutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsPut: async (
      apiV1RequestsPutRequest: ApiV1RequestsPutRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiV1RequestsPutRequest' is not null or undefined
      assertParamExists(
        "apiV1RequestsPut",
        "apiV1RequestsPutRequest",
        apiV1RequestsPutRequest,
      );
      const localVarPath = `/api/v1/requests/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiV1RequestsPutRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsRequestIdDelete: async (
      requestId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'requestId' is not null or undefined
      assertParamExists("apiV1RequestsRequestIdDelete", "requestId", requestId);
      const localVarPath = `/api/v1/requests/{requestId}`.replace(
        `{${"requestId"}}`,
        encodeURIComponent(String(requestId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsRequestIdGet: async (
      requestId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'requestId' is not null or undefined
      assertParamExists("apiV1RequestsRequestIdGet", "requestId", requestId);
      const localVarPath = `/api/v1/requests/{requestId}`.replace(
        `{${"requestId"}}`,
        encodeURIComponent(String(requestId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PaymentRequestsApi - functional programming interface
 * @export
 */
export const PaymentRequestsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    PaymentRequestsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1RequestsGet(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<ApiV1RequestsGet200ResponseInner>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1RequestsGet(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PaymentRequestsApi.apiV1RequestsGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ApiV1RequestsPostRequest} apiV1RequestsPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1RequestsPost(
      apiV1RequestsPostRequest: ApiV1RequestsPostRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiV1ProvidersPost200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1RequestsPost(
          apiV1RequestsPostRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PaymentRequestsApi.apiV1RequestsPost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ApiV1RequestsPutRequest} apiV1RequestsPutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1RequestsPut(
      apiV1RequestsPutRequest: ApiV1RequestsPutRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiV1ProvidersPost200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1RequestsPut(
          apiV1RequestsPutRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PaymentRequestsApi.apiV1RequestsPut"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1RequestsRequestIdDelete(
      requestId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1RequestsRequestIdDelete(
          requestId,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PaymentRequestsApi.apiV1RequestsRequestIdDelete"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1RequestsRequestIdGet(
      requestId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiV1RequestsRequestIdGet200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1RequestsRequestIdGet(
          requestId,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PaymentRequestsApi.apiV1RequestsRequestIdGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * PaymentRequestsApi - factory interface
 * @export
 */
export const PaymentRequestsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PaymentRequestsApiFp(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsGet(
      options?: any,
    ): AxiosPromise<Array<ApiV1RequestsGet200ResponseInner>> {
      return localVarFp
        .apiV1RequestsGet(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ApiV1RequestsPostRequest} apiV1RequestsPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsPost(
      apiV1RequestsPostRequest: ApiV1RequestsPostRequest,
      options?: any,
    ): AxiosPromise<ApiV1ProvidersPost200Response> {
      return localVarFp
        .apiV1RequestsPost(apiV1RequestsPostRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ApiV1RequestsPutRequest} apiV1RequestsPutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsPut(
      apiV1RequestsPutRequest: ApiV1RequestsPutRequest,
      options?: any,
    ): AxiosPromise<ApiV1ProvidersPost200Response> {
      return localVarFp
        .apiV1RequestsPut(apiV1RequestsPutRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsRequestIdDelete(
      requestId: string,
      options?: any,
    ): AxiosPromise<object> {
      return localVarFp
        .apiV1RequestsRequestIdDelete(requestId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsRequestIdGet(
      requestId: string,
      options?: any,
    ): AxiosPromise<ApiV1RequestsRequestIdGet200Response> {
      return localVarFp
        .apiV1RequestsRequestIdGet(requestId, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PaymentRequestsApi - object-oriented interface
 * @export
 * @class PaymentRequestsApi
 * @extends {BaseAPI}
 */
export class PaymentRequestsApi extends BaseAPI {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PaymentRequestsApi
   */
  public apiV1RequestsGet(options?: RawAxiosRequestConfig) {
    return PaymentRequestsApiFp(this.configuration)
      .apiV1RequestsGet(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ApiV1RequestsPostRequest} apiV1RequestsPostRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PaymentRequestsApi
   */
  public apiV1RequestsPost(
    apiV1RequestsPostRequest: ApiV1RequestsPostRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PaymentRequestsApiFp(this.configuration)
      .apiV1RequestsPost(apiV1RequestsPostRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ApiV1RequestsPutRequest} apiV1RequestsPutRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PaymentRequestsApi
   */
  public apiV1RequestsPut(
    apiV1RequestsPutRequest: ApiV1RequestsPutRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PaymentRequestsApiFp(this.configuration)
      .apiV1RequestsPut(apiV1RequestsPutRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} requestId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PaymentRequestsApi
   */
  public apiV1RequestsRequestIdDelete(
    requestId: string,
    options?: RawAxiosRequestConfig,
  ) {
    return PaymentRequestsApiFp(this.configuration)
      .apiV1RequestsRequestIdDelete(requestId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} requestId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PaymentRequestsApi
   */
  public apiV1RequestsRequestIdGet(
    requestId: string,
    options?: RawAxiosRequestConfig,
  ) {
    return PaymentRequestsApiFp(this.configuration)
      .apiV1RequestsRequestIdGet(requestId, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * ProvidersApi - axios parameter creator
 * @export
 */
export const ProvidersApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ProvidersGet: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/providers/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ApiV1ProvidersPostRequest} apiV1ProvidersPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ProvidersPost: async (
      apiV1ProvidersPostRequest: ApiV1ProvidersPostRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiV1ProvidersPostRequest' is not null or undefined
      assertParamExists(
        "apiV1ProvidersPost",
        "apiV1ProvidersPostRequest",
        apiV1ProvidersPostRequest,
      );
      const localVarPath = `/api/v1/providers/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiV1ProvidersPostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} providerId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ProvidersProviderIdGet: async (
      providerId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'providerId' is not null or undefined
      assertParamExists(
        "apiV1ProvidersProviderIdGet",
        "providerId",
        providerId,
      );
      const localVarPath = `/api/v1/providers/{providerId}`.replace(
        `{${"providerId"}}`,
        encodeURIComponent(String(providerId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} providerId
     * @param {ApiV1ProvidersProviderIdPutRequest} apiV1ProvidersProviderIdPutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ProvidersProviderIdPut: async (
      providerId: string,
      apiV1ProvidersProviderIdPutRequest: ApiV1ProvidersProviderIdPutRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'providerId' is not null or undefined
      assertParamExists(
        "apiV1ProvidersProviderIdPut",
        "providerId",
        providerId,
      );
      // verify required parameter 'apiV1ProvidersProviderIdPutRequest' is not null or undefined
      assertParamExists(
        "apiV1ProvidersProviderIdPut",
        "apiV1ProvidersProviderIdPutRequest",
        apiV1ProvidersProviderIdPutRequest,
      );
      const localVarPath = `/api/v1/providers/{providerId}`.replace(
        `{${"providerId"}}`,
        encodeURIComponent(String(providerId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiV1ProvidersProviderIdPutRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ProvidersApi - functional programming interface
 * @export
 */
export const ProvidersApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    ProvidersApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ProvidersGet(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<ApiV1ProvidersGet200ResponseInner>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ProvidersGet(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProvidersApi.apiV1ProvidersGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ApiV1ProvidersPostRequest} apiV1ProvidersPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ProvidersPost(
      apiV1ProvidersPostRequest: ApiV1ProvidersPostRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiV1ProvidersPost200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ProvidersPost(
          apiV1ProvidersPostRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProvidersApi.apiV1ProvidersPost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} providerId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ProvidersProviderIdGet(
      providerId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiV1ProvidersGet200ResponseInner>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ProvidersProviderIdGet(
          providerId,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProvidersApi.apiV1ProvidersProviderIdGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} providerId
     * @param {ApiV1ProvidersProviderIdPutRequest} apiV1ProvidersProviderIdPutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ProvidersProviderIdPut(
      providerId: string,
      apiV1ProvidersProviderIdPutRequest: ApiV1ProvidersProviderIdPutRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiV1ProvidersProviderIdPut200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ProvidersProviderIdPut(
          providerId,
          apiV1ProvidersProviderIdPutRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProvidersApi.apiV1ProvidersProviderIdPut"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ProvidersApi - factory interface
 * @export
 */
export const ProvidersApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ProvidersApiFp(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ProvidersGet(
      options?: any,
    ): AxiosPromise<Array<ApiV1ProvidersGet200ResponseInner>> {
      return localVarFp
        .apiV1ProvidersGet(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ApiV1ProvidersPostRequest} apiV1ProvidersPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ProvidersPost(
      apiV1ProvidersPostRequest: ApiV1ProvidersPostRequest,
      options?: any,
    ): AxiosPromise<ApiV1ProvidersPost200Response> {
      return localVarFp
        .apiV1ProvidersPost(apiV1ProvidersPostRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} providerId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ProvidersProviderIdGet(
      providerId: string,
      options?: any,
    ): AxiosPromise<ApiV1ProvidersGet200ResponseInner> {
      return localVarFp
        .apiV1ProvidersProviderIdGet(providerId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} providerId
     * @param {ApiV1ProvidersProviderIdPutRequest} apiV1ProvidersProviderIdPutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ProvidersProviderIdPut(
      providerId: string,
      apiV1ProvidersProviderIdPutRequest: ApiV1ProvidersProviderIdPutRequest,
      options?: any,
    ): AxiosPromise<ApiV1ProvidersProviderIdPut200Response> {
      return localVarFp
        .apiV1ProvidersProviderIdPut(
          providerId,
          apiV1ProvidersProviderIdPutRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ProvidersApi - object-oriented interface
 * @export
 * @class ProvidersApi
 * @extends {BaseAPI}
 */
export class ProvidersApi extends BaseAPI {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProvidersApi
   */
  public apiV1ProvidersGet(options?: RawAxiosRequestConfig) {
    return ProvidersApiFp(this.configuration)
      .apiV1ProvidersGet(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ApiV1ProvidersPostRequest} apiV1ProvidersPostRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProvidersApi
   */
  public apiV1ProvidersPost(
    apiV1ProvidersPostRequest: ApiV1ProvidersPostRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProvidersApiFp(this.configuration)
      .apiV1ProvidersPost(apiV1ProvidersPostRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} providerId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProvidersApi
   */
  public apiV1ProvidersProviderIdGet(
    providerId: string,
    options?: RawAxiosRequestConfig,
  ) {
    return ProvidersApiFp(this.configuration)
      .apiV1ProvidersProviderIdGet(providerId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} providerId
   * @param {ApiV1ProvidersProviderIdPutRequest} apiV1ProvidersProviderIdPutRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProvidersApi
   */
  public apiV1ProvidersProviderIdPut(
    providerId: string,
    apiV1ProvidersProviderIdPutRequest: ApiV1ProvidersProviderIdPutRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProvidersApiFp(this.configuration)
      .apiV1ProvidersProviderIdPut(
        providerId,
        apiV1ProvidersProviderIdPutRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * TransactionsApi - axios parameter creator
 * @export
 */
export const TransactionsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {string} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsRequestIdTransactionsGet: async (
      requestId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'requestId' is not null or undefined
      assertParamExists(
        "apiV1RequestsRequestIdTransactionsGet",
        "requestId",
        requestId,
      );
      const localVarPath = `/api/v1/requests/{requestId}/transactions`.replace(
        `{${"requestId"}}`,
        encodeURIComponent(String(requestId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ApiV1TransactionsPostRequest} apiV1TransactionsPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1TransactionsPost: async (
      apiV1TransactionsPostRequest: ApiV1TransactionsPostRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiV1TransactionsPostRequest' is not null or undefined
      assertParamExists(
        "apiV1TransactionsPost",
        "apiV1TransactionsPostRequest",
        apiV1TransactionsPostRequest,
      );
      const localVarPath = `/api/v1/transactions/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiV1TransactionsPostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} transactionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1TransactionsTransactionIdGet: async (
      transactionId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'transactionId' is not null or undefined
      assertParamExists(
        "apiV1TransactionsTransactionIdGet",
        "transactionId",
        transactionId,
      );
      const localVarPath = `/api/v1/transactions/{transactionId}`.replace(
        `{${"transactionId"}}`,
        encodeURIComponent(String(transactionId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} transactionId
     * @param {ApiV1TransactionsTransactionIdPatchRequest} apiV1TransactionsTransactionIdPatchRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1TransactionsTransactionIdPatch: async (
      transactionId: string,
      apiV1TransactionsTransactionIdPatchRequest: ApiV1TransactionsTransactionIdPatchRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'transactionId' is not null or undefined
      assertParamExists(
        "apiV1TransactionsTransactionIdPatch",
        "transactionId",
        transactionId,
      );
      // verify required parameter 'apiV1TransactionsTransactionIdPatchRequest' is not null or undefined
      assertParamExists(
        "apiV1TransactionsTransactionIdPatch",
        "apiV1TransactionsTransactionIdPatchRequest",
        apiV1TransactionsTransactionIdPatchRequest,
      );
      const localVarPath = `/api/v1/transactions/{transactionId}`.replace(
        `{${"transactionId"}}`,
        encodeURIComponent(String(transactionId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiV1TransactionsTransactionIdPatchRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TransactionsApi - functional programming interface
 * @export
 */
export const TransactionsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    TransactionsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {string} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1RequestsRequestIdTransactionsGet(
      requestId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<
        Array<ApiV1RequestsRequestIdTransactionsGet200ResponseInner>
      >
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1RequestsRequestIdTransactionsGet(
          requestId,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "TransactionsApi.apiV1RequestsRequestIdTransactionsGet"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ApiV1TransactionsPostRequest} apiV1TransactionsPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1TransactionsPost(
      apiV1TransactionsPostRequest: ApiV1TransactionsPostRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiV1TransactionsPost200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1TransactionsPost(
          apiV1TransactionsPostRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TransactionsApi.apiV1TransactionsPost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} transactionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1TransactionsTransactionIdGet(
      transactionId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiV1TransactionsTransactionIdGet200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1TransactionsTransactionIdGet(
          transactionId,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "TransactionsApi.apiV1TransactionsTransactionIdGet"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} transactionId
     * @param {ApiV1TransactionsTransactionIdPatchRequest} apiV1TransactionsTransactionIdPatchRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1TransactionsTransactionIdPatch(
      transactionId: string,
      apiV1TransactionsTransactionIdPatchRequest: ApiV1TransactionsTransactionIdPatchRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1TransactionsTransactionIdPatch(
          transactionId,
          apiV1TransactionsTransactionIdPatchRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "TransactionsApi.apiV1TransactionsTransactionIdPatch"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * TransactionsApi - factory interface
 * @export
 */
export const TransactionsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = TransactionsApiFp(configuration);
  return {
    /**
     *
     * @param {string} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1RequestsRequestIdTransactionsGet(
      requestId: string,
      options?: any,
    ): AxiosPromise<
      Array<ApiV1RequestsRequestIdTransactionsGet200ResponseInner>
    > {
      return localVarFp
        .apiV1RequestsRequestIdTransactionsGet(requestId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ApiV1TransactionsPostRequest} apiV1TransactionsPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1TransactionsPost(
      apiV1TransactionsPostRequest: ApiV1TransactionsPostRequest,
      options?: any,
    ): AxiosPromise<ApiV1TransactionsPost200Response> {
      return localVarFp
        .apiV1TransactionsPost(apiV1TransactionsPostRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} transactionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1TransactionsTransactionIdGet(
      transactionId: string,
      options?: any,
    ): AxiosPromise<ApiV1TransactionsTransactionIdGet200Response> {
      return localVarFp
        .apiV1TransactionsTransactionIdGet(transactionId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} transactionId
     * @param {ApiV1TransactionsTransactionIdPatchRequest} apiV1TransactionsTransactionIdPatchRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1TransactionsTransactionIdPatch(
      transactionId: string,
      apiV1TransactionsTransactionIdPatchRequest: ApiV1TransactionsTransactionIdPatchRequest,
      options?: any,
    ): AxiosPromise<object> {
      return localVarFp
        .apiV1TransactionsTransactionIdPatch(
          transactionId,
          apiV1TransactionsTransactionIdPatchRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TransactionsApi - object-oriented interface
 * @export
 * @class TransactionsApi
 * @extends {BaseAPI}
 */
export class TransactionsApi extends BaseAPI {
  /**
   *
   * @param {string} requestId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TransactionsApi
   */
  public apiV1RequestsRequestIdTransactionsGet(
    requestId: string,
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .apiV1RequestsRequestIdTransactionsGet(requestId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ApiV1TransactionsPostRequest} apiV1TransactionsPostRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TransactionsApi
   */
  public apiV1TransactionsPost(
    apiV1TransactionsPostRequest: ApiV1TransactionsPostRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .apiV1TransactionsPost(apiV1TransactionsPostRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} transactionId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TransactionsApi
   */
  public apiV1TransactionsTransactionIdGet(
    transactionId: string,
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .apiV1TransactionsTransactionIdGet(transactionId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} transactionId
   * @param {ApiV1TransactionsTransactionIdPatchRequest} apiV1TransactionsTransactionIdPatchRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TransactionsApi
   */
  public apiV1TransactionsTransactionIdPatch(
    transactionId: string,
    apiV1TransactionsTransactionIdPatchRequest: ApiV1TransactionsTransactionIdPatchRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TransactionsApiFp(this.configuration)
      .apiV1TransactionsTransactionIdPatch(
        transactionId,
        apiV1TransactionsTransactionIdPatchRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
