openapi: 3.0.3
info:
  title: OGCIO Profile API
  description: API for OGCIO Profile Service
  version: 0.1.0
components:
  schemas: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: Default Response
  /api/v1/addresses/:
    get:
      tags:
        - Addresses
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    address_id:
                      type: string
                    address_line1:
                      type: string
                    address_line2:
                      type: string
                    town:
                      type: string
                    county:
                      type: string
                    eirecode:
                      type: string
                    updated_at:
                      type: string
                    move_in_date:
                      type: string
                    move_out_date:
                      type: string
                    is_primary:
                      type: boolean
                    ownership_status:
                      type: string
                  required:
                    - address_id
                    - address_line1
                    - address_line2
                    - town
                    - county
                    - eirecode
                    - updated_at
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
    post:
      tags:
        - Addresses
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address_line1:
                  type: string
                address_line2:
                  type: string
                town:
                  type: string
                county:
                  type: string
                eirecode:
                  type: string
                move_in_date:
                  type: string
                move_out_date:
                  type: string
              required:
                - address_line1
                - town
                - county
                - eirecode
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
  /api/v1/addresses/{addressId}:
    get:
      tags:
        - Addresses
      parameters:
        - schema:
            type: string
          in: path
          name: addressId
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  address_id:
                    type: string
                  address_line1:
                    type: string
                  address_line2:
                    type: string
                  town:
                    type: string
                  county:
                    type: string
                  eirecode:
                    type: string
                  updated_at:
                    type: string
                  move_in_date:
                    type: string
                  move_out_date:
                    type: string
                  is_primary:
                    type: boolean
                  ownership_status:
                    type: string
                required:
                  - address_id
                  - address_line1
                  - address_line2
                  - town
                  - county
                  - eirecode
                  - updated_at
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
    put:
      tags:
        - Addresses
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address_line1:
                  type: string
                address_line2:
                  type: string
                town:
                  type: string
                county:
                  type: string
                eirecode:
                  type: string
                move_in_date:
                  type: string
                move_out_date:
                  type: string
                is_primary:
                  type: boolean
                ownership_status:
                  type: string
      parameters:
        - schema:
            type: string
          in: path
          name: addressId
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
    delete:
      tags:
        - Addresses
      parameters:
        - schema:
            type: string
          in: path
          name: addressId
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
  /api/v1/entitlements/:
    get:
      tags:
        - Entitlements
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    firstname:
                      type: string
                    lastname:
                      type: string
                    type:
                      type: string
                    issue_date:
                      type: string
                    expiry_date:
                      type: string
                    document_number:
                      type: string
                  required:
                    - firstname
                    - lastname
                    - type
                    - issue_date
                    - document_number
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
  /api/v1/user/:
    get:
      tags:
        - User
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstname:
                    type: string
                  lastname:
                    type: string
                  email:
                    type: string
                  title:
                    type: string
                  date_of_birth:
                    type: string
                  ppsn:
                    type: string
                  ppsn_visible:
                    type: boolean
                  gender:
                    type: string
                  phone:
                    type: string
                  consent_to_prefill_data:
                    type: boolean
                required:
                  - firstname
                  - lastname
                  - email
                  - title
                  - ppsn
                  - ppsn_visible
                  - gender
                  - phone
                  - consent_to_prefill_data
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
    post:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                title:
                  type: string
                date_of_birth:
                  type: string
                ppsn:
                  type: string
                ppsn_visible:
                  type: boolean
                gender:
                  type: string
                phone:
                  type: string
                consent_to_prefill_data:
                  type: boolean
              required:
                - firstname
                - lastname
                - email
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
    put:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                title:
                  type: string
                date_of_birth:
                  type: string
                ppsn:
                  type: string
                ppsn_visible:
                  type: boolean
                gender:
                  type: string
                phone:
                  type: string
                consent_to_prefill_data:
                  type: boolean
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  time:
                    type: string
                required:
                  - statusCode
                  - code
                  - error
                  - message
                  - time
tags:
  - name: User
  - name: Addresses
  - name: Entitlements
