variables:
  awsServiceConnection: life-events-dev-ecr
  awsRegion: eu-west-1
  ecrEndpoint: 730335224023.dkr.ecr.eu-west-1.amazonaws.com
  environment: LifeEvents-dev

  nextPublicStripePublishableKey: pk_test_51OzFkUK1VL0xyyr2E3EvcEmzsAGLowKH3jlM4g3AhQwUjhlpxQvfjZizc5GRSAnNzf8HHwTdzhz2rRYS69nooxtg00ZF7kRvyN
  nextPublicHostUrl: https://payments.dev.blocks.gov.ie/
  nextPublicApiEndpoint: https://api.dev.blocks.gov.ie
  nextPublicMessagingServiceEntryPoint: https://messaging.dev.blocks.gov.ie
  nextPublicPaymentsServiceEntryPoint: https://payments.dev.blocks.gov.ie
  nextPublicLifeEventsServiceEntryPoint: https://dev.life.gov.ie
  nextPublicBuildingBlocksLandingPage: https://dev.blocks.gov.ie
  nextPublicFormsUrl: https://www.forms.uat.gov.ie/
  nextPublicMatomoUrl: //analytics.ogcio.gov.ie
  nextPublicMatomoProtocol: https
  nextPublicLifeEventsMatomoSiteId: 11
  nextPublicBuildingBlocksMatomoSiteId: 14
