variables:
  awsServiceConnection: life-events-dev-ecr
  awsRegion: eu-west-1
  ecrEndpoint: 730335224023.dkr.ecr.eu-west-1.amazonaws.com
  nextPublicStripePublishableKey: pk_test_51OzFkUK1VL0xyyr2E3EvcEmzsAGLowKH3jlM4g3AhQwUjhlpxQvfjZizc5GRSAnNzf8HHwTdzhz2rRYS69nooxtg00ZF7kRvyN
  nextPublicHostUrl: https://payments.dev.blocks.gov.ie/
  nextPublicApiEndpoint: https://api.dev.blocks.gov.ie
  nextPublicMessagingServiceEntryPoint: https://messaging.dev.blocks.gov.ie/
  nextPublicPaymentsServiceEntryPoint: https://payments.dev.blocks.gov.ie/
  nextPublicLifeEventsServiceEntryPoint: https://dev.life.gov.ie/
  nextPublicBuildingBlocksLandingPage: https://blocks.gov.ie/
  authServiceUrl: https://auth.dev.blocks.gov.ie/
  nextPublicFormsUrl: https://www.formsg.testing.gov.ie/
