openapi: 3.0.3
info:
  title: OGCIO AuthService
  description: API for OGCIO AuthService
  version: 0.1.0
components:
  schemas: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: Default Response
  /auth/:
    get:
      tags:
        - Auth
      parameters:
        - schema:
            type: string
          in: query
          name: redirectUrl
          required: false
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  request_id:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - request_id
                  - name
  /auth/logout:
    get:
      tags:
        - Auth
      parameters:
        - schema:
            type: string
          in: query
          name: redirectUrl
          required: false
      responses:
        "302":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  headers:
                    location:
                      type: string
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  request_id:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - request_id
                  - name
  /auth/callback:
    get:
      tags:
        - Auth
      parameters:
        - schema:
            type: string
          in: query
          name: code
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "302":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  headers:
                    location:
                      type: string
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  request_id:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - request_id
                  - name
  /users/:
    get:
      tags:
        - Users
      responses:
        "200":
          description: Default Response
  /session/validate:
    get:
      parameters:
        - schema:
            type: string
          in: query
          name: sessionId
          required: true
      responses:
        "200":
          description: Default Response
tags:
  - name: AuthService
