openapi: 3.0.3
info:
  title: OGCIO Integrator API
  description: API for OGCIO Integrator Service
  version: 0.1.0
components:
  schemas: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: Default Response
  /api/v1/journeys/:
    get:
      tags: &a1
        - Journeys
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        userId:
                          type: string
                        organizationId:
                          type: string
                        status:
                          anyOf:
                            - type: string
                              enum:
                                - active
                            - type: string
                              enum:
                                - draft
                      required:
                        - id
                        - title
                        - userId
                        - organizationId
                        - status
                  metadata:
                    type: object
                    properties:
                      links:
                        type: object
                        properties:
                          self:
                            type: object
                            properties:
                              href:
                                type: string
                          next:
                            type: object
                            properties:
                              href:
                                type: string
                          prev:
                            type: object
                            properties:
                              href:
                                type: string
                          first:
                            type: object
                            properties:
                              href:
                                type: string
                          last:
                            type: object
                            properties:
                              href:
                                type: string
                          pages:
                            type: object
                            additionalProperties:
                              type: object
                              properties:
                                href:
                                  type: string
                        required:
                          - self
                          - first
                          - last
                          - pages
                      totalCount:
                        type: number
                required:
                  - data
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
    post:
      tags: *a1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                organizationId:
                  type: string
                userId:
                  type: string
              required:
                - title
                - organizationId
                - userId
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                    required:
                      - id
                  metadata:
                    type: object
                    properties:
                      links:
                        type: object
                        properties:
                          self:
                            type: object
                            properties:
                              href:
                                type: string
                          next:
                            type: object
                            properties:
                              href:
                                type: string
                          prev:
                            type: object
                            properties:
                              href:
                                type: string
                          first:
                            type: object
                            properties:
                              href:
                                type: string
                          last:
                            type: object
                            properties:
                              href:
                                type: string
                          pages:
                            type: object
                            additionalProperties:
                              type: object
                              properties:
                                href:
                                  type: string
                        required:
                          - self
                          - first
                          - last
                          - pages
                      totalCount:
                        type: number
                required:
                  - data
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
  /api/v1/journeys/{journeyId}:
    get:
      tags: *a1
      parameters:
        - schema:
            type: string
          in: path
          name: journeyId
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      userId:
                        type: string
                      organizationId:
                        type: string
                      status:
                        anyOf:
                          - type: string
                            enum:
                              - active
                          - type: string
                            enum:
                              - draft
                    required:
                      - id
                      - title
                      - userId
                      - organizationId
                      - status
                  metadata:
                    type: object
                    properties:
                      links:
                        type: object
                        properties:
                          self:
                            type: object
                            properties:
                              href:
                                type: string
                          next:
                            type: object
                            properties:
                              href:
                                type: string
                          prev:
                            type: object
                            properties:
                              href:
                                type: string
                          first:
                            type: object
                            properties:
                              href:
                                type: string
                          last:
                            type: object
                            properties:
                              href:
                                type: string
                          pages:
                            type: object
                            additionalProperties:
                              type: object
                              properties:
                                href:
                                  type: string
                        required:
                          - self
                          - first
                          - last
                          - pages
                      totalCount:
                        type: number
                required:
                  - data
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
    patch:
      tags: *a1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  anyOf:
                    - type: string
                      enum:
                        - active
                    - type: string
                      enum:
                        - draft
                initialStepId:
                  type: string
              required:
                - status
                - initialStepId
        required: true
      parameters:
        - schema:
            type: string
          in: path
          name: journeyId
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                    required:
                      - id
                  metadata:
                    type: object
                    properties:
                      links:
                        type: object
                        properties:
                          self:
                            type: object
                            properties:
                              href:
                                type: string
                          next:
                            type: object
                            properties:
                              href:
                                type: string
                          prev:
                            type: object
                            properties:
                              href:
                                type: string
                          first:
                            type: object
                            properties:
                              href:
                                type: string
                          last:
                            type: object
                            properties:
                              href:
                                type: string
                          pages:
                            type: object
                            additionalProperties:
                              type: object
                              properties:
                                href:
                                  type: string
                        required:
                          - self
                          - first
                          - last
                          - pages
                      totalCount:
                        type: number
                required:
                  - data
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
  /api/v1/journeys/{journeyId}/public-info:
    get:
      tags: *a1
      parameters:
        - schema:
            type: string
          in: path
          name: journeyId
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      userId:
                        type: string
                      organizationId:
                        type: string
                      status:
                        anyOf:
                          - type: string
                            enum:
                              - active
                          - type: string
                            enum:
                              - draft
                    required:
                      - id
                      - title
                      - userId
                      - organizationId
                      - status
                  metadata:
                    type: object
                    properties:
                      links:
                        type: object
                        properties:
                          self:
                            type: object
                            properties:
                              href:
                                type: string
                          next:
                            type: object
                            properties:
                              href:
                                type: string
                          prev:
                            type: object
                            properties:
                              href:
                                type: string
                          first:
                            type: object
                            properties:
                              href:
                                type: string
                          last:
                            type: object
                            properties:
                              href:
                                type: string
                          pages:
                            type: object
                            additionalProperties:
                              type: object
                              properties:
                                href:
                                  type: string
                        required:
                          - self
                          - first
                          - last
                          - pages
                      totalCount:
                        type: number
                required:
                  - data
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  detail:
                    type: string
                  requestId:
                    type: string
                  name:
                    type: string
                  validation: {}
                  validationContext:
                    type: string
                required:
                  - code
                  - detail
                  - requestId
                  - name
tags:
  - name: Integrator
