/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/messages/jobs/{id}": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Default Response */
        202: {
          content: never;
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
  "/api/v1/messages/": {
    get: {
      parameters: {
        query?: {
          type?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                id: string;
                subject: string;
                excerpt: string;
                plainText: string;
                richText: string;
                createdAt: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            preferredTransports: string[];
            userIds: string[];
            security: string;
            /** Format: date-time */
            scheduleAt: string;
            message?: {
              threadName?: string;
              messageName: string;
              subject: string;
              excerpt: string;
              richText: string;
              plainText: string;
              lang: string;
            };
            template?: {
              /** Format: uuid */
              id: string;
              interpolations: {
                [key: string]: string;
              };
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
  "/api/v1/messages/{messageId}": {
    get: {
      parameters: {
        path: {
          messageId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                subject: string;
                excerpt: string;
                plainText: string;
                richText: string;
              };
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
  "/api/v1/messages/template": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            templateMetaId: string;
            userIds: string[];
            transportations: ("email" | "sms" | "lifeEvent")[];
            security: string;
            /** Format: date-time */
            scheduleAt: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/providers/emails/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                name: string;
                host: string;
                port: number;
                username: string;
                password: string;
                throttle?: number;
                fromAddress: string;
                ssl: boolean;
              }[];
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            host: string;
            port: number;
            username: string;
            password: string;
            throttle?: number;
            fromAddress: string;
            ssl: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
              };
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/providers/emails/{providerId}": {
    get: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                name: string;
                host: string;
                port: number;
                username: string;
                password: string;
                throttle?: number;
                fromAddress: string;
                ssl: boolean;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            name: string;
            host: string;
            port: number;
            username: string;
            password: string;
            throttle?: number;
            fromAddress: string;
            ssl: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      responses: {
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/providers/sms/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                name: string;
                type: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            config: {
              type: string;
              accessKey: string;
              secretAccessKey: string;
              region: string;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
  "/api/v1/providers/sms/{providerId}": {
    get: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data?: {
                /** Format: uuid */
                id: string;
                name: string;
                config: {
                  type: string;
                  accessKey: string;
                  secretAccessKey: string;
                  region: string;
                };
              };
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            name: string;
            config: {
              type: string;
              accessKey: string;
              secretAccessKey: string;
              region: string;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      responses: {
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
  "/api/v1/templates/": {
    get: {
      parameters: {
        query?: {
          lang?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                templateMetaId: string;
                contents: {
                  lang: string;
                  templateName: string;
                }[];
              }[];
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            contents: {
              templateName: string;
              lang: string;
              subject: string;
              excerpt: string;
              plainText: string;
              richText: string;
            }[];
            variables: {
              name: string;
              type: string;
              languages: string[];
            }[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
              };
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
  "/api/v1/templates/{templateId}": {
    get: {
      parameters: {
        path: {
          templateId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                contents: {
                  templateName: string;
                  subject: string;
                  excerpt: string;
                  plainText: string;
                  richText: string;
                  lang: string;
                }[];
                fields: {
                  fieldName: string;
                  fieldType: string;
                }[];
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          templateId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            contents: {
              /** Format: uuid */
              id: string;
              templateName: string;
              lang: string;
              subject: string;
              excerpt: string;
              plainText: string;
              richText: string;
            }[];
            variables: {
              name: string;
              type: string;
            }[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          templateId: string;
        };
      };
      responses: {
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
  "/api/v1/users/settings/organisations": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                id: string;
                /** @default null */
                userProfileId: string | null;
                organisationId: string;
                /** @default pending */
                organisationInvitationStatus:
                  | "to_be_invited"
                  | "pending"
                  | "accepted"
                  | "declined";
                organisationInvitationSentAt?: string;
                organisationInvitationFeedbackAt?: string;
                organisationPreferredTransports?: string[];
                correlationQuality: "full" | "partial" | "not_related";
                /** @default pending */
                userStatus: "to_be_invited" | "pending" | "disabled" | "active";
                /** @default null */
                phone: null | string;
                /** @default null */
                email: null | string;
                details?: {
                  /** @default null */
                  publicIdentityId: null | string;
                  /** @default null */
                  firstName: null | string;
                  /** @default null */
                  lastName: null | string;
                  /** @default null */
                  birthDate: null | string;
                  /** @default null */
                  address: {
                    /** @default null */
                    city: null | string;
                    /** @default null */
                    zipCode: null | string;
                    /** @default null */
                    street: null | string;
                    /** @default null */
                    country: null | string;
                    /** @default null */
                    region: null | string;
                  } | null;
                  /** @default false */
                  collectedConsent: boolean;
                };
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/settings/organisations/{organisationId}": {
    get: {
      parameters: {
        path: {
          organisationId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                id: string;
                /** @default null */
                userProfileId: string | null;
                organisationId: string;
                /** @default pending */
                organisationInvitationStatus:
                  | "to_be_invited"
                  | "pending"
                  | "accepted"
                  | "declined";
                organisationInvitationSentAt?: string;
                organisationInvitationFeedbackAt?: string;
                organisationPreferredTransports?: string[];
                correlationQuality: "full" | "partial" | "not_related";
                /** @default pending */
                userStatus: "to_be_invited" | "pending" | "disabled" | "active";
                /** @default null */
                phone: null | string;
                /** @default null */
                email: null | string;
                details?: {
                  /** @default null */
                  publicIdentityId: null | string;
                  /** @default null */
                  firstName: null | string;
                  /** @default null */
                  lastName: null | string;
                  /** @default null */
                  birthDate: null | string;
                  /** @default null */
                  address: {
                    /** @default null */
                    city: null | string;
                    /** @default null */
                    zipCode: null | string;
                    /** @default null */
                    street: null | string;
                    /** @default null */
                    country: null | string;
                    /** @default null */
                    region: null | string;
                  } | null;
                  /** @default false */
                  collectedConsent: boolean;
                };
              };
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          organisationId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** @default accepted */
            invitationStatusFeedback: "accepted" | "declined";
            preferredTransports: string[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        202: {
          content: {
            "application/json": {
              data: {
                id: string;
                /** @default null */
                userProfileId: string | null;
                organisationId: string;
                /** @default pending */
                organisationInvitationStatus:
                  | "to_be_invited"
                  | "pending"
                  | "accepted"
                  | "declined";
                organisationInvitationSentAt?: string;
                organisationInvitationFeedbackAt?: string;
                organisationPreferredTransports?: string[];
                correlationQuality: "full" | "partial" | "not_related";
                /** @default pending */
                userStatus: "to_be_invited" | "pending" | "disabled" | "active";
                /** @default null */
                phone: null | string;
                /** @default null */
                email: null | string;
                details?: {
                  /** @default null */
                  publicIdentityId: null | string;
                  /** @default null */
                  firstName: null | string;
                  /** @default null */
                  lastName: null | string;
                  /** @default null */
                  birthDate: null | string;
                  /** @default null */
                  address: {
                    /** @default null */
                    city: null | string;
                    /** @default null */
                    zipCode: null | string;
                    /** @default null */
                    street: null | string;
                    /** @default null */
                    country: null | string;
                    /** @default null */
                    region: null | string;
                  } | null;
                  /** @default false */
                  collectedConsent: boolean;
                };
              };
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/settings/invitations/me": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                /** @default pending */
                userStatus: "to_be_invited" | "pending" | "disabled" | "active";
              };
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
    patch: {
      requestBody: {
        content: {
          "application/json": {
            /** @default active */
            userStatusFeedback: "disabled" | "active";
          };
        };
      };
      responses: {
        /** @description Default Response */
        202: {
          content: {
            "application/json": {
              data: {
                id?: string;
                /** @default null */
                userProfileId: null | string;
                importerOrganisationId: string;
                /** @default pending */
                userStatus: "to_be_invited" | "pending" | "disabled" | "active";
                correlationQuality: "full" | "partial" | "not_related";
                /** @default null */
                phone: null | string;
                /** @default null */
                email: null | string;
                details?: {
                  /** @default null */
                  publicIdentityId: null | string;
                  /** @default null */
                  firstName: null | string;
                  /** @default null */
                  lastName: null | string;
                  /** @default null */
                  birthDate: null | string;
                  /** @default null */
                  address: {
                    /** @default null */
                    city: null | string;
                    /** @default null */
                    zipCode: null | string;
                    /** @default null */
                    street: null | string;
                    /** @default null */
                    country: null | string;
                    /** @default null */
                    region: null | string;
                  } | null;
                  /** @default false */
                  collectedConsent: boolean;
                };
                /** @default null */
                usersImportId: null | string;
              };
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/imports/csv": {
    post: {
      responses: {
        /** @description Default Response */
        202: {
          content: never;
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/imports/csv/template": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/api/v1/users/imports/": {
    get: {
      parameters: {
        query?: {
          organisationId?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                organisationId: string;
                /** Format: date-time */
                importedAt: string;
                /** @default api */
                importChannel: "api" | "csv";
                /** @default 0 */
                retryCount: number;
                /** @default null */
                lastRetryAt: string | null;
                importId: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": {
            importIndex: number;
            /** @default null */
            publicIdentityId?: null | string;
            /** @default null */
            firstName?: null | string;
            /** @default null */
            lastName?: null | string;
            /** @default null */
            phoneNumber?: null | string;
            /** @default null */
            birthDate?: null | string;
            /** @default null */
            emailAddress?: null | string;
            /** @default null */
            addressCity?: null | string;
            /** @default null */
            addressZipCode?: null | string;
            /** @default null */
            addressStreet?: null | string;
            /** @default null */
            addressCountry?: null | string;
            /** @default null */
            addressRegion?: null | string;
            /** @default null */
            tags?: null | string;
            /** @default null */
            collectedConsent?: null | string;
          }[];
        };
      };
      responses: {
        /** @description Default Response */
        202: {
          content: never;
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/imports/users": {
    get: {
      parameters: {
        query?: {
          organisationId?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                id: string;
                /** @default null */
                userProfileId: string | null;
                organisationId: string;
                /** @default pending */
                organisationInvitationStatus:
                  | "to_be_invited"
                  | "pending"
                  | "accepted"
                  | "declined";
                organisationInvitationSentAt?: string;
                organisationInvitationFeedbackAt?: string;
                organisationPreferredTransports?: string[];
                correlationQuality: "full" | "partial" | "not_related";
                /** @default pending */
                userStatus: "to_be_invited" | "pending" | "disabled" | "active";
                /** @default null */
                phone: null | string;
                /** @default null */
                email: null | string;
                details?: {
                  /** @default null */
                  publicIdentityId: null | string;
                  /** @default null */
                  firstName: null | string;
                  /** @default null */
                  lastName: null | string;
                  /** @default null */
                  birthDate: null | string;
                  /** @default null */
                  address: {
                    /** @default null */
                    city: null | string;
                    /** @default null */
                    zipCode: null | string;
                    /** @default null */
                    street: null | string;
                    /** @default null */
                    country: null | string;
                    /** @default null */
                    region: null | string;
                  } | null;
                  /** @default false */
                  collectedConsent: boolean;
                };
              }[];
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/imports/{importId}": {
    get: {
      parameters: {
        query: {
          organisationId?: string;
          includeUsersData: boolean;
        };
        path: {
          importId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                organisationId: string;
                /** Format: date-time */
                importedAt: string;
                usersData: {
                  importIndex: number;
                  /** @default null */
                  phoneNumber: null | string;
                  /** @default null */
                  emailAddress: null | string;
                  /** @default pending */
                  importStatus:
                    | "pending"
                    | "imported"
                    | "not_found"
                    | "error"
                    | "missing_contacts";
                  /** @default null */
                  importError?: null | string;
                  /** @default null */
                  relatedUserProfileId?: null | string;
                  /** @default null */
                  relatedUserId?: null | string;
                  tags?: string[];
                  /** @default null */
                  publicIdentityId: null | string;
                  /** @default null */
                  firstName: null | string;
                  /** @default null */
                  lastName: null | string;
                  /** @default null */
                  birthDate: null | string;
                  /** @default null */
                  address: {
                    /** @default null */
                    city: null | string;
                    /** @default null */
                    zipCode: null | string;
                    /** @default null */
                    street: null | string;
                    /** @default null */
                    country: null | string;
                    /** @default null */
                    region: null | string;
                  } | null;
                  /** @default false */
                  collectedConsent: boolean;
                }[];
                /** @default api */
                importChannel: "api" | "csv";
                /** @default 0 */
                retryCount: number;
                /** @default null */
                lastRetryAt: string | null;
                importId: string;
              };
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/imports/{importId}/users": {
    get: {
      parameters: {
        query?: {
          organisationId?: string;
        };
        path: {
          importId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                id: string;
                /** @default null */
                userProfileId: string | null;
                organisationId: string;
                /** @default pending */
                organisationInvitationStatus:
                  | "to_be_invited"
                  | "pending"
                  | "accepted"
                  | "declined";
                organisationInvitationSentAt?: string;
                organisationInvitationFeedbackAt?: string;
                organisationPreferredTransports?: string[];
                correlationQuality: "full" | "partial" | "not_related";
                /** @default pending */
                userStatus: "to_be_invited" | "pending" | "disabled" | "active";
                /** @default null */
                phone: null | string;
                /** @default null */
                email: null | string;
                details?: {
                  /** @default null */
                  publicIdentityId: null | string;
                  /** @default null */
                  firstName: null | string;
                  /** @default null */
                  lastName: null | string;
                  /** @default null */
                  birthDate: null | string;
                  /** @default null */
                  address: {
                    /** @default null */
                    city: null | string;
                    /** @default null */
                    zipCode: null | string;
                    /** @default null */
                    street: null | string;
                    /** @default null */
                    country: null | string;
                    /** @default null */
                    region: null | string;
                  } | null;
                  /** @default false */
                  collectedConsent: boolean;
                };
              }[];
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/imports/mock-organisation-id": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              data: string;
            };
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": {
              code: string;
              detail: string;
              request_id: string;
              name: string;
              validation?: {
                fieldName: string;
                message: string;
              }[];
              validationContext?: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HttpError */
    "def-0": {
      statusCode?: number;
      code?: string;
      error?: string;
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
