/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/messages/": {
    get: {
      parameters: {
        query?: {
          type?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                id: string;
                subject: string;
                excerpt: string;
                plainText: string;
                richText: string;
                links: string[];
                createdAt: string;
                messageType: string;
                paymentRequestId?: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": {
            message?: {
              threadName?: string;
              messageName: string;
              subject: string;
              excerpt: string;
              richText: string;
              plainText: string;
              links: string[];
              /** Format: uuid */
              paymentRequestId?: string;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
  "/api/v1/messages/{messageId}": {
    get: {
      parameters: {
        path: {
          messageId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: {
                subject: string;
                excerpt: string;
                plainText: string;
                richText: string;
                links: string[];
                paymentRequestId?: string;
              };
            };
          };
        };
        /** @description Default Response */
        "4XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
        /** @description Default Response */
        "5XX": {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HttpError */
    "def-0": {
      statusCode?: number;
      code?: string;
      error?: string;
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
