import axios from "axios";
import { PaymentRequestsApi, ProvidersApi } from "./autogenerated";
import { getAuthCookie } from "../libraries/auth";

const buildAxiosInstance = (userId) => {
  const instance = axios.create({});
  instance.defaults.headers.common["x-user-id"] = userId;
  instance.defaults.headers.common["x-logto-auth"] = getAuthCookie();

  return instance;
};

export default (userId) => {
  return {
    providers: new ProvidersApi(
      undefined,
      process.env.BACKEND_URL,
      buildAxiosInstance(userId),
    ),
    paymentRequests: new PaymentRequestsApi(
      undefined,
      process.env.BACKEND_URL,
      buildAxiosInstance(userId),
    ),
  };
};
