import axios from "axios";
import {
  PaymentRequestsApi,
  ProvidersApi,
  TransactionsApi,
} from "./autogenerated";

const buildAxiosInstance = (token) => {
  const instance = axios.create({});
  // x-user-id for mock auth
  instance.defaults.headers.common["x-user-id"] = token;
  // Bearer token for logto auth
  instance.defaults.headers.common["Authorization"] = `Bearer ${token}`;

  return instance;
};

export default (token: string) => {
  return {
    providers: new ProvidersApi(
      undefined,
      process.env.BACKEND_URL,
      buildAxiosInstance(token),
    ),
    paymentRequests: new PaymentRequestsApi(
      undefined,
      process.env.BACKEND_URL,
      buildAxiosInstance(token),
    ),
    transactions: new TransactionsApi(
      undefined,
      process.env.BACKEND_URL,
      buildAxiosInstance(token),
    ),
  };
};
