import axios from "axios";
import { ProvidersApi } from "./autogenerated";

const buildAxiosInstance = (userId) => {
  const instance = axios.create({});
  instance.defaults.headers.common["x-user-id"] = userId;
  return instance;
};

const backendUrl = "http://localhost:8001";

export default (userId) => {
  return {
    providers: new ProvidersApi(
      undefined,
      backendUrl,
      buildAxiosInstance(userId),
    ),
  };
};
