/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/providers/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              name: string;
              type: string;
              data: unknown;
              status: string;
            }[];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            type: "banktransfer" | "openbanking" | "stripe";
            data: unknown;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/providers/{providerId}": {
    get: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              name: string;
              type: string;
              data: unknown;
              status: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            data: unknown;
            status: "connected" | "disconnected";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              ok: boolean;
            };
          };
        };
      };
    };
  };
  "/api/v1/requests/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              paymentRequestId: string;
              title: string;
              description: string;
              amount: number;
              reference: string;
              providers: {
                userId: string;
                id: string;
                name: string;
                type: string;
                status: string;
                data: unknown;
                createdAt: string;
              }[];
            }[];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description: string;
            reference: string;
            amount: number;
            redirectUrl: string;
            allowAmountOverride: boolean;
            allowCustomAmount: boolean;
            providers: string[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/requests/{requestId}": {
    get: {
      parameters: {
        path: {
          requestId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              paymentRequestId: string;
              title: string;
              description: string;
              amount: number;
              reference: string;
              providers: {
                userId: string;
                id: string;
                name: string;
                type: string;
                status: string;
                data: unknown;
                createdAt: string;
              }[];
              redirectUrl: string;
              allowAmountOverride: boolean;
              allowCustomAmount: boolean;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {};
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
