/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/providers/banktransfer": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @enum {string} */
            type: "banktransfer";
            data: {
              iban: string;
              accountHolderName: string;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/providers/openbanking": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @enum {string} */
            type: "openbanking";
            data: {
              iban: string;
              accountHolderName: string;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/providers/stripe": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @enum {string} */
            type: "stripe";
            data: {
              livePublishableKey: string;
              liveSecretKey: string;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/providers/worldpay": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @enum {string} */
            type: "worldpay";
            data: {
              merchantCode: string;
              installationId: string;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/providers/realex": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @enum {string} */
            type: "realex";
            data: {
              merchantId: string;
              sharedSecret: string;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/providers/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              name: string;
              type: string;
              data: unknown;
              status: string;
            }[];
          };
        };
      };
    };
  };
  "/api/v1/providers/{providerId}": {
    get: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              name: string;
              type: string;
              data: unknown;
              status: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            data: unknown;
            status: "connected" | "disconnected";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              ok: boolean;
            };
          };
        };
      };
    };
  };
  "/api/v1/requests/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              paymentRequestId: string;
              title: string;
              description: string;
              amount: number;
              reference: string;
              status: "active" | "inactive";
              providers: {
                userId: string;
                id: string;
                name: string;
                type: "banktransfer" | "openbanking" | "stripe" | "realex";
                status: "connected" | "disconnected";
                data: unknown;
                createdAt: string;
              }[];
            }[];
          };
        };
      };
    };
    put: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description: string;
            reference: string;
            amount: number;
            redirectUrl: string;
            allowAmountOverride: boolean;
            allowCustomAmount: boolean;
            status: "active" | "inactive";
            paymentRequestId: string;
            providersUpdate: {
              toDisable: string[];
              toCreate: string[];
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description: string;
            reference: string;
            amount: number;
            redirectUrl: string;
            allowAmountOverride: boolean;
            allowCustomAmount: boolean;
            providers: string[];
            status: "active" | "inactive";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/requests/{requestId}": {
    get: {
      parameters: {
        path: {
          requestId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              paymentRequestId: string;
              title: string;
              description: string;
              amount: number;
              reference: string;
              status: "active" | "inactive";
              providers: {
                userId: string;
                id: string;
                name: string;
                type: "banktransfer" | "openbanking" | "stripe" | "realex";
                status: "connected" | "disconnected";
                data: unknown;
                createdAt: string;
              }[];
              redirectUrl: string;
              allowAmountOverride: boolean;
              allowCustomAmount: boolean;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          requestId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/requests/{requestId}/public-info": {
    get: {
      parameters: {
        path: {
          requestId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              paymentRequestId: string;
              title: string;
              description: string;
              amount: number;
              reference: string;
              status: string;
              providers: {
                userId: string;
                id: string;
                name: string;
                type: "banktransfer" | "openbanking" | "stripe" | "realex";
                status: "connected" | "disconnected";
                data: unknown;
                createdAt: string;
              }[];
              redirectUrl: string;
              allowAmountOverride: boolean;
              allowCustomAmount: boolean;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/requests/{requestId}/transactions": {
    get: {
      parameters: {
        path: {
          requestId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              transactionId: string;
              status:
                | "initiated"
                | "pending"
                | "succeeded"
                | "cancelled"
                | "failed";
              amount: number;
              updatedAt: string;
              title: string;
            }[];
          };
        };
      };
    };
  };
  "/api/v1/transactions/{transactionId}": {
    get: {
      parameters: {
        path: {
          transactionId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              transactionId: string;
              status:
                | "initiated"
                | "pending"
                | "succeeded"
                | "cancelled"
                | "failed";
              amount: number;
              updatedAt: string;
              title: string;
              extPaymentId: string;
              userId: string;
              userData: {
                name: string;
                email: string;
              };
              providerName: string;
              providerType: string;
              paymentRequestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          transactionId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            status:
              | "initiated"
              | "pending"
              | "succeeded"
              | "cancelled"
              | "failed";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/v1/transactions/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              transactionId: string;
              status:
                | "initiated"
                | "pending"
                | "succeeded"
                | "cancelled"
                | "failed";
              amount: number;
              updatedAt: string;
              title: string;
              extPaymentId: string;
              userId: string;
              userData: {
                name: string;
                email: string;
              };
              providerName: string;
              providerType: string;
              paymentRequestId: string;
            }[];
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            paymentRequestId: string;
            extPaymentId: string;
            integrationReference: string;
            amount: number;
            paymentProviderId: string;
            userData: {
              name: string;
              email: string;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              transactionId: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/transactions/generatePaymentIntentId": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              intentId: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/citizen/transactions": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              transactionId: string;
              status:
                | "initiated"
                | "pending"
                | "succeeded"
                | "cancelled"
                | "failed";
              title: string;
              updatedAt: string;
              amount: number;
            }[];
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/citizen/transactions/{transactionId}": {
    get: {
      parameters: {
        path: {
          transactionId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              transactionId: string;
              status:
                | "initiated"
                | "pending"
                | "succeeded"
                | "cancelled"
                | "failed";
              amount: number;
              updatedAt: string;
              title: string;
              extPaymentId: string;
              userId: string;
              userData: {
                name: string;
                email: string;
              };
              providerName: string;
              providerType: string;
              paymentRequestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/realex/paymentObject": {
    get: {
      parameters: {
        query: {
          amount: string;
          intentId: string;
          providerId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              ACCOUNT: string;
              AMOUNT: string;
              CURRENCY: string;
              MERCHANT_ID: string;
              ORDER_ID: string;
              TIMESTAMP: string;
              URL: string;
              SHA256HASH: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/realex/verifyPaymentResponse": {
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": string;
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {};
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
