/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/auth/": {
    get: {
      parameters: {
        query?: {
          redirectUrl?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": string;
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/auth/logout": {
    get: {
      parameters: {
        query?: {
          redirectUrl?: string;
        };
      };
      responses: {
        /** @description Default Response */
        302: {
          content: {
            "application/json": {
              headers?: unknown;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/auth/callback": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            public_servant?: string;
            id_token: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        302: {
          content: {
            "application/json": {
              headers?: unknown;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              statusCode: number;
              code: string;
              error: string;
              message: string;
              time: string;
            };
          };
        };
      };
    };
  };
  "/users/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/session/validate": {
    get: {
      parameters: {
        query: {
          sessionId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {};
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
