/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/providers/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              name: string;
              type: "banktransfer" | "openbanking" | "stripe";
              data: unknown;
              status: string;
            }[];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            type: "banktransfer" | "openbanking" | "stripe";
            data: unknown;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/providers/{providerId}": {
    get: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              name: string;
              type: string;
              data: unknown;
              status: string;
            };
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          providerId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            data: unknown;
            status: "connected" | "disconnected";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              ok: boolean;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {};
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
